"""Configuration for the Quotex Signal Bot."""

# All 100 instruments from Quotex platform with their symbols, categories, payouts and IDs.
# These are dynamically updated when connected to Quotex WebSocket.
QUOTEX_INSTRUMENTS = {
    # ─── Forex ───
    "AUDCAD": {"id": 36, "name": "AUD/CAD", "category": "currency", "decimals": 5, "payout": 45, "is_otc": False},
    "AUDCHF": {"id": 37, "name": "AUD/CHF", "category": "currency", "decimals": 5, "payout": 20, "is_otc": False},
    "AUDJPY": {"id": 38, "name": "AUD/JPY", "category": "currency", "decimals": 3, "payout": 50, "is_otc": False},
    "AUDUSD": {"id": 40, "name": "AUD/USD", "category": "currency", "decimals": 5, "payout": 50, "is_otc": False},
    "CADJPY": {"id": 42, "name": "CAD/JPY", "category": "currency", "decimals": 3, "payout": 65, "is_otc": False},
    "CHFJPY": {"id": 43, "name": "CHF/JPY", "category": "currency", "decimals": 3, "payout": 20, "is_otc": False},
    "EURAUD": {"id": 44, "name": "EUR/AUD", "category": "currency", "decimals": 5, "payout": 20, "is_otc": False},
    "EURCAD": {"id": 45, "name": "EUR/CAD", "category": "currency", "decimals": 5, "payout": 20, "is_otc": False},
    "EURCHF": {"id": 46, "name": "EUR/CHF", "category": "currency", "decimals": 5, "payout": 20, "is_otc": False},
    "EURGBP": {"id": 47, "name": "EUR/GBP", "category": "currency", "decimals": 5, "payout": 40, "is_otc": False},
    "EURJPY": {"id": 48, "name": "EUR/JPY", "category": "currency", "decimals": 3, "payout": 73, "is_otc": False},
    "EURUSD": {"id": 1, "name": "EUR/USD", "category": "currency", "decimals": 5, "payout": 65, "is_otc": False},
    "GBPAUD": {"id": 51, "name": "GBP/AUD", "category": "currency", "decimals": 5, "payout": 40, "is_otc": False},
    "GBPCAD": {"id": 52, "name": "GBP/CAD", "category": "currency", "decimals": 5, "payout": 40, "is_otc": False},
    "GBPCHF": {"id": 53, "name": "GBP/CHF", "category": "currency", "decimals": 5, "payout": 40, "is_otc": False},
    "GBPJPY": {"id": 54, "name": "GBP/JPY", "category": "currency", "decimals": 3, "payout": 40, "is_otc": False},
    "GBPUSD": {"id": 56, "name": "GBP/USD", "category": "currency", "decimals": 5, "payout": 45, "is_otc": False},
    "USDCAD": {"id": 61, "name": "USD/CAD", "category": "currency", "decimals": 5, "payout": 40, "is_otc": False},
    "USDCHF": {"id": 62, "name": "USD/CHF", "category": "currency", "decimals": 5, "payout": 40, "is_otc": False},
    "USDJPY": {"id": 63, "name": "USD/JPY", "category": "currency", "decimals": 3, "payout": 76, "is_otc": False},
    # ─── Forex OTC ───
    "AUDCAD_otc": {"id": 67, "name": "AUD/CAD (OTC)", "category": "currency", "decimals": 5, "payout": 90, "is_otc": True},
    "AUDCHF_otc": {"id": 68, "name": "AUD/CHF (OTC)", "category": "currency", "decimals": 5, "payout": 77, "is_otc": True},
    "AUDJPY_otc": {"id": 69, "name": "AUD/JPY (OTC)", "category": "currency", "decimals": 3, "payout": 77, "is_otc": True},
    "AUDNZD_otc": {"id": 70, "name": "AUD/NZD (OTC)", "category": "currency", "decimals": 5, "payout": 92, "is_otc": True},
    "AUDUSD_otc": {"id": 71, "name": "AUD/USD (OTC)", "category": "currency", "decimals": 5, "payout": 81, "is_otc": True},
    "CADCHF_otc": {"id": 72, "name": "CAD/CHF (OTC)", "category": "currency", "decimals": 5, "payout": 92, "is_otc": True},
    "CADJPY_otc": {"id": 73, "name": "CAD/JPY (OTC)", "category": "currency", "decimals": 3, "payout": 72, "is_otc": True},
    "CHFJPY_otc": {"id": 74, "name": "CHF/JPY (OTC)", "category": "currency", "decimals": 3, "payout": 82, "is_otc": True},
    "EURAUD_otc": {"id": 75, "name": "EUR/AUD (OTC)", "category": "currency", "decimals": 5, "payout": 93, "is_otc": True},
    "EURCAD_otc": {"id": 76, "name": "EUR/CAD (OTC)", "category": "currency", "decimals": 5, "payout": 77, "is_otc": True},
    "EURCHF_otc": {"id": 77, "name": "EUR/CHF (OTC)", "category": "currency", "decimals": 5, "payout": 77, "is_otc": True},
    "EURGBP_otc": {"id": 78, "name": "EUR/GBP (OTC)", "category": "currency", "decimals": 5, "payout": 85, "is_otc": True},
    "EURJPY_otc": {"id": 79, "name": "EUR/JPY (OTC)", "category": "currency", "decimals": 3, "payout": 77, "is_otc": True},
    "EURNZD_otc": {"id": 80, "name": "EUR/NZD (OTC)", "category": "currency", "decimals": 5, "payout": 78, "is_otc": True},
    "EURUSD_otc": {"id": 66, "name": "EUR/USD (OTC)", "category": "currency", "decimals": 5, "payout": 87, "is_otc": True},
    "GBPAUD_otc": {"id": 81, "name": "GBP/AUD (OTC)", "category": "currency", "decimals": 5, "payout": 92, "is_otc": True},
    "GBPCAD_otc": {"id": 82, "name": "GBP/CAD (OTC)", "category": "currency", "decimals": 5, "payout": 92, "is_otc": True},
    "GBPCHF_otc": {"id": 83, "name": "GBP/CHF (OTC)", "category": "currency", "decimals": 5, "payout": 51, "is_otc": True},
    "GBPJPY_otc": {"id": 84, "name": "GBP/JPY (OTC)", "category": "currency", "decimals": 3, "payout": 77, "is_otc": True},
    "GBPNZD_otc": {"id": 85, "name": "GBP/NZD (OTC)", "category": "currency", "decimals": 5, "payout": 67, "is_otc": True},
    "GBPUSD_otc": {"id": 86, "name": "GBP/USD (OTC)", "category": "currency", "decimals": 5, "payout": 85, "is_otc": True},
    "NZDCAD_otc": {"id": 87, "name": "NZD/CAD (OTC)", "category": "currency", "decimals": 5, "payout": 75, "is_otc": True},
    "NZDCHF_otc": {"id": 88, "name": "NZD/CHF (OTC)", "category": "currency", "decimals": 5, "payout": 81, "is_otc": True},
    "NZDJPY_otc": {"id": 89, "name": "NZD/JPY (OTC)", "category": "currency", "decimals": 3, "payout": 89, "is_otc": True},
    "NZDUSD_otc": {"id": 90, "name": "NZD/USD (OTC)", "category": "currency", "decimals": 5, "payout": 92, "is_otc": True},
    "USDCAD_otc": {"id": 91, "name": "USD/CAD (OTC)", "category": "currency", "decimals": 5, "payout": 92, "is_otc": True},
    "USDCHF_otc": {"id": 92, "name": "USD/CHF (OTC)", "category": "currency", "decimals": 5, "payout": 91, "is_otc": True},
    "USDJPY_otc": {"id": 93, "name": "USD/JPY (OTC)", "category": "currency", "decimals": 3, "payout": 77, "is_otc": True},
    # ─── Exotic Currency OTC ───
    "BRLUSD_otc": {"id": 332, "name": "USD/BRL (OTC)", "category": "currency", "decimals": 5, "payout": 94, "is_otc": True},
    "USDARS_otc": {"id": 345, "name": "USD/ARS (OTC)", "category": "currency", "decimals": 2, "payout": 87, "is_otc": True},
    "USDBDT_otc": {"id": 334, "name": "USD/BDT (OTC)", "category": "currency", "decimals": 3, "payout": 89, "is_otc": True},
    "USDCOP_otc": {"id": 347, "name": "USD/COP (OTC)", "category": "currency", "decimals": 2, "payout": 87, "is_otc": True},
    "USDDZD_otc": {"id": 349, "name": "USD/DZD (OTC)", "category": "currency", "decimals": 3, "payout": 77, "is_otc": True},
    "USDEGP_otc": {"id": 338, "name": "USD/EGP (OTC)", "category": "currency", "decimals": 4, "payout": 77, "is_otc": True},
    "USDIDR_otc": {"id": 342, "name": "USD/IDR (OTC)", "category": "currency", "decimals": 2, "payout": 88, "is_otc": True},
    "USDINR_otc": {"id": 202, "name": "USD/INR (OTC)", "category": "currency", "decimals": 4, "payout": 75, "is_otc": True},
    "USDMXN_otc": {"id": 343, "name": "USD/MXN (OTC)", "category": "currency", "decimals": 5, "payout": 77, "is_otc": True},
    "USDNGN_otc": {"id": 340, "name": "USD/NGN (OTC)", "category": "currency", "decimals": 2, "payout": 81, "is_otc": True},
    "USDPHP_otc": {"id": 351, "name": "USD/PHP (OTC)", "category": "currency", "decimals": 3, "payout": 87, "is_otc": True},
    "USDPKR_otc": {"id": 336, "name": "USD/PKR (OTC)", "category": "currency", "decimals": 3, "payout": 86, "is_otc": True},
    "USDZAR_otc": {"id": 157, "name": "USD/ZAR (OTC)", "category": "currency", "decimals": 5, "payout": 67, "is_otc": True},
    # ─── Crypto OTC ───
    "BTCUSD_otc": {"id": 352, "name": "Bitcoin (OTC)", "category": "cryptocurrency", "decimals": 2, "payout": 92, "is_otc": True},
    "ETHUSD_otc": {"id": 360, "name": "Ethereum (OTC)", "category": "cryptocurrency", "decimals": 2, "payout": 62, "is_otc": True},
    "LTCUSD_otc": {"id": 361, "name": "Litecoin (OTC)", "category": "cryptocurrency", "decimals": 2, "payout": 92, "is_otc": True},
    "BNBUSD_otc": {"id": 362, "name": "Binance Coin (OTC)", "category": "cryptocurrency", "decimals": 2, "payout": 84, "is_otc": True},
    "BCHUSD_otc": {"id": 363, "name": "Bitcoin Cash (OTC)", "category": "cryptocurrency", "decimals": 2, "payout": 92, "is_otc": True},
    "XRPUSD_otc": {"id": 364, "name": "Ripple (OTC)", "category": "cryptocurrency", "decimals": 4, "payout": 81, "is_otc": True},
    "SOLUSD_otc": {"id": 365, "name": "Solana (OTC)", "category": "cryptocurrency", "decimals": 2, "payout": 87, "is_otc": True},
    "TONUSD_otc": {"id": 366, "name": "Toncoin (OTC)", "category": "cryptocurrency", "decimals": 4, "payout": 92, "is_otc": True},
    "TRUUSD_otc": {"id": 359, "name": "Trump (OTC)", "category": "cryptocurrency", "decimals": 4, "payout": 92, "is_otc": True},
    "ATOUSD_otc": {"id": 368, "name": "Cosmos (OTC)", "category": "cryptocurrency", "decimals": 4, "payout": 84, "is_otc": True},
    "DASUSD_otc": {"id": 369, "name": "Dash (OTC)", "category": "cryptocurrency", "decimals": 3, "payout": 71, "is_otc": True},
    "ETCUSD_otc": {"id": 370, "name": "Ethereum Classic (OTC)", "category": "cryptocurrency", "decimals": 3, "payout": 87, "is_otc": True},
    "DOTUSD_otc": {"id": 374, "name": "Polkadot (OTC)", "category": "cryptocurrency", "decimals": 4, "payout": 84, "is_otc": True},
    "AVAUSD_otc": {"id": 379, "name": "Avalanche (OTC)", "category": "cryptocurrency", "decimals": 3, "payout": 37, "is_otc": True},
    "AXSUSD_otc": {"id": 380, "name": "Axie Infinity (OTC)", "category": "cryptocurrency", "decimals": 4, "payout": 84, "is_otc": True},
    "LINUSD_otc": {"id": 383, "name": "Chainlink (OTC)", "category": "cryptocurrency", "decimals": 3, "payout": 67, "is_otc": True},
    "ZECUSD_otc": {"id": 375, "name": "Zcash (OTC)", "category": "cryptocurrency", "decimals": 2, "payout": 69, "is_otc": True},
    # ─── Commodity ───
    "XAUUSD": {"id": 2, "name": "Gold", "category": "commodity", "decimals": 3, "payout": 20, "is_otc": False},
    "XAGUSD": {"id": 65, "name": "Silver", "category": "commodity", "decimals": 3, "payout": 20, "is_otc": False},
    # ─── Commodity OTC ───
    "XAUUSD_otc": {"id": 169, "name": "Gold (OTC)", "category": "commodity", "decimals": 3, "payout": 81, "is_otc": True},
    "XAGUSD_otc": {"id": 167, "name": "Silver (OTC)", "category": "commodity", "decimals": 4, "payout": 92, "is_otc": True},
    "UKBrent_otc": {"id": 164, "name": "UKBrent (OTC)", "category": "commodity", "decimals": 3, "payout": 77, "is_otc": True},
    "USCrude_otc": {"id": 165, "name": "USCrude (OTC)", "category": "commodity", "decimals": 3, "payout": 77, "is_otc": True},
    # ─── Stock ───
    "AXJAUD": {"id": 315, "name": "S&P/ASX 200", "category": "stock", "decimals": 0, "payout": 20, "is_otc": False},
    "F40EUR": {"id": 318, "name": "CAC 40", "category": "stock", "decimals": 1, "payout": 20, "is_otc": False},
    "FTSGBP": {"id": 319, "name": "FTSE 100", "category": "stock", "decimals": 1, "payout": 20, "is_otc": False},
    "HSIHKD": {"id": 320, "name": "Hong Kong 50", "category": "stock", "decimals": 0, "payout": 20, "is_otc": False},
    "IBXEUR": {"id": 321, "name": "IBEX 35", "category": "stock", "decimals": 0, "payout": 20, "is_otc": False},
    "JPXJPY": {"id": 327, "name": "Nikkei 225", "category": "stock", "decimals": 2, "payout": 20, "is_otc": False},
    "CHIA50": {"id": 328, "name": "FTSE China A50", "category": "stock", "decimals": 0, "payout": 20, "is_otc": False},
    "STXEUR": {"id": 325, "name": "EURO STOXX 50", "category": "stock", "decimals": 1, "payout": 20, "is_otc": False},
    # ─── Stock OTC ───
    "AXP_otc": {"id": 291, "name": "American Express (OTC)", "category": "stock", "decimals": 3, "payout": 77, "is_otc": True},
    "BA_otc": {"id": 292, "name": "Boeing Company (OTC)", "category": "stock", "decimals": 2, "payout": 88, "is_otc": True},
    "FB_otc": {"id": 187, "name": "FACEBOOK INC (OTC)", "category": "stock", "decimals": 2, "payout": 77, "is_otc": True},
    "INTC_otc": {"id": 190, "name": "Intel (OTC)", "category": "stock", "decimals": 3, "payout": 92, "is_otc": True},
    "JNJ_otc": {"id": 296, "name": "Johnson & Johnson (OTC)", "category": "stock", "decimals": 3, "payout": 85, "is_otc": True},
    "MCD_otc": {"id": 175, "name": "McDonald's (OTC)", "category": "stock", "decimals": 3, "payout": 92, "is_otc": True},
    "MSFT_otc": {"id": 176, "name": "Microsoft (OTC)", "category": "stock", "decimals": 3, "payout": 83, "is_otc": True},
    "PFE_otc": {"id": 297, "name": "Pfizer Inc (OTC)", "category": "stock", "decimals": 3, "payout": 77, "is_otc": True},
}

# yfinance symbols for chart data (OTC pairs use same base symbol)
YF_SYMBOLS = {
    # Forex
    "EURUSD": "EURUSD=X", "GBPUSD": "GBPUSD=X", "USDJPY": "JPY=X",
    "AUDUSD": "AUDUSD=X", "EURGBP": "EURGBP=X", "USDCAD": "CAD=X",
    "EURJPY": "EURJPY=X", "GBPJPY": "GBPJPY=X", "CHFJPY": "CHFJPY=X",
    "USDCHF": "CHF=X", "AUDCAD": "AUDCAD=X", "AUDJPY": "AUDJPY=X",
    "AUDCHF": "AUDCHF=X", "CADJPY": "CADJPY=X", "EURAUD": "EURAUD=X",
    "EURCAD": "EURCAD=X", "EURCHF": "EURCHF=X", "GBPAUD": "GBPAUD=X",
    "GBPCAD": "GBPCAD=X", "GBPCHF": "GBPCHF=X",
    # Crypto
    "BTCUSD_otc": "BTC-USD", "ETHUSD_otc": "ETH-USD",
    "LTCUSD_otc": "LTC-USD", "BNBUSD_otc": "BNB-USD",
    "BCHUSD_otc": "BCH-USD", "XRPUSD_otc": "XRP-USD",
    "SOLUSD_otc": "SOL-USD", "AVAUSD_otc": "AVAX-USD",
    "DOTUSD_otc": "DOT-USD", "LINUSD_otc": "LINK-USD",
    "ATOUSD_otc": "ATOM-USD", "ETCUSD_otc": "ETC-USD",
    "DASUSD_otc": "DASH-USD", "ZECUSD_otc": "ZEC-USD",
    "TONUSD_otc": "TON11419-USD", "AXSUSD_otc": "AXS-USD",
    # Commodity
    "XAUUSD": "GC=F", "XAGUSD": "SI=F",
    "UKBrent_otc": "BZ=F", "USCrude_otc": "CL=F",
    # Stock indices
    "AXJAUD": "^AXJO", "F40EUR": "^FCHI", "FTSGBP": "^FTSE",
    "HSIHKD": "^HSI", "IBXEUR": "^IBEX", "JPXJPY": "^N225",
    "STXEUR": "^STOXX50E",
    # Stock OTC
    "AXP_otc": "AXP", "BA_otc": "BA", "FB_otc": "META",
    "INTC_otc": "INTC", "JNJ_otc": "JNJ", "MCD_otc": "MCD",
    "MSFT_otc": "MSFT", "PFE_otc": "PFE",
}

TIMEFRAMES = {
    "1m": {"yf_interval": "1m", "yf_period": "1d", "label": "1 Minute"},
    "5m": {"yf_interval": "5m", "yf_period": "5d", "label": "5 Minutes"},
    "15m": {"yf_interval": "15m", "yf_period": "5d", "label": "15 Minutes"},
    "1h": {"yf_interval": "1h", "yf_period": "1mo", "label": "1 Hour"},
}

SIGNAL_THRESHOLDS = {
    "rsi_overbought": 70,
    "rsi_oversold": 30,
    "rsi_period": 14,
    "ema_fast": 9,
    "ema_slow": 21,
    "macd_fast": 12,
    "macd_slow": 26,
    "macd_signal": 9,
    "bb_period": 20,
    "bb_std": 2.0,
    "stoch_k": 14,
    "stoch_d": 3,
    "stoch_overbought": 80,
    "stoch_oversold": 20,
}

# Category display mapping
CATEGORY_DISPLAY = {
    "currency": {"regular": "Forex", "otc": "Forex OTC"},
    "cryptocurrency": {"regular": "Crypto", "otc": "Crypto OTC"},
    "commodity": {"regular": "Commodity", "otc": "Commodity OTC"},
    "stock": {"regular": "Stock", "otc": "Stock OTC"},
}
